/********************************************************************
* cuts_emptyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error cuts_emptyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecuts_emptyDict();
extern void G__cpp_setup_inheritancecuts_emptyDict();
extern void G__cpp_setup_typetablecuts_emptyDict();
extern void G__cpp_setup_memvarcuts_emptyDict();
extern void G__cpp_setup_globalcuts_emptyDict();
extern void G__cpp_setup_memfunccuts_emptyDict();
extern void G__cpp_setup_funccuts_emptyDict();
extern void G__set_cpp_environmentcuts_emptyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "cuts_empty.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__cuts_emptyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__cuts_emptyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__cuts_emptyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__cuts_emptyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__cuts_emptyDictLN_cuts_empty;

/* STUB derived class for protected member access */
